### ISSUE TITLE
Stolen graphics

### ISSUE THREAD

**Issue by EarendelGames** [pandamiami80s/Armored-Train-Turret-Wagons#2]
You are using graphics stolen from AAI Vehicles Warden. This is against the licence of that mod. Please remove them immediatly.

**Comment by pandamiami80s** [comment]
Hello. Will do

**Comment by EarendelGames** [comment]
Thanks, if you need replacement sprites you may find that the radar-like top of the old beacon graphics are suitable.

**Comment by pandamiami80s** [comment]
Thank you for messaging me. I did not read license to your mod actually. I
will change my mod during this weekend.
